/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-02-05 05:54:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import com.example.util.DBUtil;

public final class adminLeaveManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.example.util.DBUtil");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Admin Leave Management</title>\r\n");
      out.write("    <style>\r\n");
      out.write("      body { font-family: Arial, sans-serif; background-color: #f8f9fa; }\r\n");
      out.write("      .container { max-width: 900px; margin: 50px auto; background: #fff; padding: 20px; border: 1px solid #dee2e6; border-radius: 5px; }\r\n");
      out.write("      h2 { margin-bottom: 20px; }\r\n");
      out.write("      .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }\r\n");
      out.write("      .table th, .table td { border: 1px solid #dee2e6; padding: 8px; text-align: left; }\r\n");
      out.write("      .table th { background-color: #f1f1f1; }\r\n");
      out.write("      .btn { padding: 5px 10px; border: none; border-radius: 4px; background-color: #007bff; color: white; text-decoration: none; cursor: pointer; margin-right: 5px; }\r\n");
      out.write("      .btn:hover { background-color: #0056b3; }\r\n");
      out.write("      .btn-danger { background-color: #dc3545; }\r\n");
      out.write("      .btn-danger:hover { background-color: #c82333; }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h2>Admin Leave Management</h2>\r\n");
      out.write("      <table class=\"table\">\r\n");
      out.write("        <thead>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th>Leave ID</th>\r\n");
      out.write("            <th>Employee ID</th>\r\n");
      out.write("            <th>Manager ID</th>\r\n");
      out.write("            <th>Start Date</th>\r\n");
      out.write("            <th>End Date</th>\r\n");
      out.write("            <th>Reason</th>\r\n");
      out.write("            <th>Status</th>\r\n");
      out.write("            <th>Actions</th>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("          ");

             try(Connection conn = DBUtil.getConnection()){
                String sql = "SELECT * FROM leaves";
                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(sql);
                while(rs.next()){
          
      out.write("\r\n");
      out.write("          <tr>\r\n");
      out.write("             <td>");
      out.print( rs.getInt("id") );
      out.write("</td>\r\n");
      out.write("             <td>");
      out.print( rs.getInt("employee_id") );
      out.write("</td>\r\n");
      out.write("             <td>");
      out.print( rs.getInt("manager_id") );
      out.write("</td>\r\n");
      out.write("             <td>");
      out.print( rs.getDate("start_date") );
      out.write("</td>\r\n");
      out.write("             <td>");
      out.print( rs.getDate("end_date") );
      out.write("</td>\r\n");
      out.write("             <td>");
      out.print( rs.getString("reason") );
      out.write("</td>\r\n");
      out.write("             <td>");
      out.print( rs.getString("status") );
      out.write("</td>\r\n");
      out.write("             <td>\r\n");
      out.write("                <a href=\"editLeave.jsp?id=");
      out.print( rs.getInt("id") );
      out.write("\" class=\"btn\">Edit</a>\r\n");
      out.write("                <a href=\"deleteLeave.jsp?id=");
      out.print( rs.getInt("id") );
      out.write("\" class=\"btn btn-danger\">Delete</a>\r\n");
      out.write("             </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          ");

                }
             } catch(Exception e){
                e.printStackTrace();
             }
          
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("      <a href=\"adminDashboard.jsp\" class=\"btn\">Back to Dashboard</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
