/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-02-05 05:27:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import com.example.util.DBUtil;

public final class applyLeave_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.example.util.DBUtil");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    // Ensure that only an employee can access this page
    String role = (String) session.getAttribute("role");
    if (role == null || !role.equals("employee")) {
        response.sendRedirect("login.jsp");
    }

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Apply Leave</title>\r\n");
      out.write("    <style>\r\n");
      out.write("      /* Styling for the apply leave page */\r\n");
      out.write("      body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        background-color: #f8f9fa;\r\n");
      out.write("      }\r\n");
      out.write("      .container {\r\n");
      out.write("        max-width: 600px;\r\n");
      out.write("        margin: 50px auto;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #dee2e6;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("      }\r\n");
      out.write("      .header {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("      }\r\n");
      out.write("      h2 {\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("      }\r\n");
      out.write("      .form-label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("      .form-control {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        border: 1px solid #ced4da;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("      }\r\n");
      out.write("      .btn {\r\n");
      out.write("        padding: 10px 15px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        background-color: #007bff;\r\n");
      out.write("        color: white;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      .btn:hover {\r\n");
      out.write("        background-color: #0056b3;\r\n");
      out.write("      }\r\n");
      out.write("      .alert {\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        background-color: #d1ecf1;\r\n");
      out.write("        border: 1px solid #bee5eb;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        color: #0c5460;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"header\">\r\n");
      out.write("         <h2>Apply for Leave</h2>\r\n");
      out.write("         <a href=\"logout.jsp\" class=\"btn\" style=\"background-color: #dc3545;\">Logout</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      ");
 if(request.getParameter("msg") != null) { 
      out.write("\r\n");
      out.write("         <div class=\"alert\">");
      out.print( request.getParameter("msg") );
      out.write("</div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("      <form action=\"applyLeave\" method=\"post\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <label class=\"form-label\">Start Date:</label>\r\n");
      out.write("          <input type=\"date\" name=\"start_date\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <label class=\"form-label\">End Date:</label>\r\n");
      out.write("          <input type=\"date\" name=\"end_date\" class=\"form-control\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <label class=\"form-label\">Reason:</label>\r\n");
      out.write("          <textarea name=\"reason\" class=\"form-control\" required></textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <label class=\"form-label\">Select Manager:</label>\r\n");
      out.write("          <select name=\"manager_id\" class=\"form-control\" required>\r\n");
      out.write("            <option value=\"\">--Select Manager--</option>\r\n");
      out.write("            ");

              // Populate the manager drop-down from the database
              try (Connection conn = DBUtil.getConnection()) {
                  String sql = "SELECT id, username FROM users WHERE role = 'manager'";
                  PreparedStatement ps = conn.prepareStatement(sql);
                  ResultSet rs = ps.executeQuery();
                  while (rs.next()) {
            
      out.write("\r\n");
      out.write("            <option value=\"");
      out.print( rs.getInt("id") );
      out.write('"');
      out.write('>');
      out.print( rs.getString("username") );
      out.write("</option>\r\n");
      out.write("            ");

                  }
              } catch (Exception e) {
                  e.printStackTrace();
              }
            
      out.write("\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button type=\"submit\" class=\"btn\">Submit Leave Request</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
