/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-02-05 05:45:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import com.example.util.DBUtil;

public final class managerDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.example.util.DBUtil");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    // Ensure that only a manager can access this page
    String role = (String) session.getAttribute("role");
    if (role == null || !role.equals("manager")) {
        response.sendRedirect("login.jsp");
    }
    int managerId = (Integer) session.getAttribute("userId");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Manager Dashboard</title>\r\n");
      out.write("    <style>\r\n");
      out.write("      /* Styling for the manager dashboard */\r\n");
      out.write("      body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        background-color: #f8f9fa;\r\n");
      out.write("      }\r\n");
      out.write("      .container {\r\n");
      out.write("        max-width: 900px;\r\n");
      out.write("        margin: 50px auto;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #dee2e6;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("      }\r\n");
      out.write("      .header {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("      }\r\n");
      out.write("      h2, h3 {\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("      }\r\n");
      out.write("      .nav-tabs {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin: 0 0 20px 0;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        border-bottom: 1px solid #dee2e6;\r\n");
      out.write("      }\r\n");
      out.write("      .nav-tabs li {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      .nav-tabs a {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        padding: 10px 15px;\r\n");
      out.write("        border: 1px solid transparent;\r\n");
      out.write("        border-radius: 4px 4px 0 0;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #007bff;\r\n");
      out.write("      }\r\n");
      out.write("      .nav-tabs a.active,\r\n");
      out.write("      .nav-tabs a:hover {\r\n");
      out.write("        border-color: #dee2e6 #dee2e6 #fff;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("      }\r\n");
      out.write("      .table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("      }\r\n");
      out.write("      .table th, .table td {\r\n");
      out.write("        border: 1px solid #dee2e6;\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("      }\r\n");
      out.write("      .table th {\r\n");
      out.write("        background-color: #f1f1f1;\r\n");
      out.write("      }\r\n");
      out.write("      .btn {\r\n");
      out.write("        padding: 5px 10px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        background-color: #007bff;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size: 0.9em;\r\n");
      out.write("      }\r\n");
      out.write("      .btn:hover {\r\n");
      out.write("        background-color: #0056b3;\r\n");
      out.write("      }\r\n");
      out.write("      .btn-danger {\r\n");
      out.write("        background-color: #dc3545;\r\n");
      out.write("      }\r\n");
      out.write("      .btn-danger:hover {\r\n");
      out.write("        background-color: #c82333;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"header\">\r\n");
      out.write("         <h2>Manager Dashboard - Welcome, ");
      out.print( session.getAttribute("username") );
      out.write("</h2>\r\n");
      out.write("         ");
 if(request.getParameter("msg") != null) { 
      out.write("\r\n");
      out.write("         <div class=\"alert\">");
      out.print( request.getParameter("msg") );
      out.write("</div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("         <a href=\"logout.jsp\" class=\"btn\">Logout</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <ul class=\"nav-tabs\">\r\n");
      out.write("        <li><a class=\"active\" href=\"managerDashboard.jsp\">Pending Leaves</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <div>\r\n");
      out.write("        <h3>Pending Leave Requests</h3>\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("          <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>Leave ID</th>\r\n");
      out.write("              <th>Employee Name</th>\r\n");
      out.write("              <th>Start Date</th>\r\n");
      out.write("              <th>End Date</th>\r\n");
      out.write("              <th>Reason</th>\r\n");
      out.write("              <th>Status</th>\r\n");
      out.write("              <th>Actions</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </thead>\r\n");
      out.write("          <tbody>\r\n");
      out.write("            ");

              // Fetch pending leaves for this manager
              try (Connection conn = DBUtil.getConnection()) {
                  String sql = "SELECT l.id, l.start_date, l.end_date, l.reason, l.status, u.username " +
                               "FROM leaves l JOIN users u ON l.employee_id = u.id " +
                               "WHERE l.manager_id = ? AND l.status = 'pending'";
                  PreparedStatement ps = conn.prepareStatement(sql);
                  ps.setInt(1, managerId);
                  ResultSet rs = ps.executeQuery();
                  while (rs.next()) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>");
      out.print( rs.getInt("id") );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( rs.getString("username") );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( rs.getDate("start_date") );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( rs.getDate("end_date") );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( rs.getString("reason") );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( rs.getString("status") );
      out.write("</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <a href=\"approveLeave?id=");
      out.print( rs.getInt("id") );
      out.write("&action=approve\" class=\"btn\">Approve</a>\r\n");
      out.write("                <a href=\"approveLeave?id=");
      out.print( rs.getInt("id") );
      out.write("&action=reject\" class=\"btn btn-danger\">Reject</a>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                  }
              } catch (Exception e) {
                  e.printStackTrace();
              }
            
      out.write("\r\n");
      out.write("          </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
